name: autoencoder_grav_large
type: autoencoder
dataset: grav
preprocessing_method: autoencoder
hidden_dims: [160, 80]
latent_dim: 14
lr: 1.0e-3
lr_decay: 0.5
lr_decay_patience: 12
betas: [0.99, 0.999]
weight_decay: 1.0e-4
batch_size: 65536
epochs: 1000
stagnant_epoch_patience: 20
gradient_clipping: 2.0
dropout: 0.3
dropout_decay_patience: 10
dropout_reduction_factor: 0.1
noise: 0.1
shuffle_chunk_size: 0.1

latents_minmax_path: outputs/weights/${name}/latents_minmax.npy
power_weight: 20
conservation_weight: 100
